services:
  db:
    image: postgres:15
    container_name: fastapi_notes_final_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fastapi_notes_final_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
    command: sh -c "alembic upgrade head && uvicorn notes.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
