services:
  db:
    image: postgres:15
    container_name: fastapi_notes_final_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fastapi_notes_final_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fastapi_notes_final_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      REDIS_URL: ${REDIS_URL}
    command: sh -c "alembic upgrade head && uvicorn notes.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
